# return user data(default omar because there is no auth yet)
GET http://127.0.0.1:8000/user/


### Get Settings
PUT http://127.0.0.1:8000/user/
Content-Type: application/json

{
    "font": "omar"
}

### GET leaderboard
GET http://127.0.0.1:8000/leaderboard/

