# Generated by Django 5.2 on 2025-04-16 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='vscode', max_length=30)),
                ('font', models.CharField(choices=[('ibm', 'ibm'), ('jetbrains', 'jetbrains'), ('helvetica', 'helvetica'), ('ubuntu', 'ubuntu'), ('roboto', 'roboto')], default='default', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qpm', models.IntegerField()),
                ('raw', models.IntegerField()),
                ('accuracy', models.SmallIntegerField()),
                ('mode', models.CharField(choices=[('questions', 'questions'), ('time', 'time')], max_length=10)),
                ('difficulty', models.SmallIntegerField()),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
