# Generated by Django 5.2 on 2025-04-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_test_number_test_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='font',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='settings',
            name='theme',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='test',
            name='mode',
            field=models.CharField(max_length=10),
        ),
    ]
