# Generated by Django 5.2 on 2025-04-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_settings_font_alter_settings_theme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='mode',
            field=models.CharField(choices=[('questions', 'questions'), ('time', 'time')], max_length=10),
        ),
    ]
