# Generated by Django 5.2 on 2025-04-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_test_number_alter_test_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='qpm',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='test',
            name='raw',
            field=models.FloatField(),
        ),
    ]
